# Generated by Django 3.2.12 on 2022-04-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goods',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
