# Generated by Django 3.2.12 on 2022-04-22 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20220420_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
